#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ejercicios")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void Insertautomovil(automovil instance);
  partial void Updateautomovil(automovil instance);
  partial void Deleteautomovil(automovil instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EjerciciosConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<automovil> automovil
	{
		get
		{
			return this.GetTable<automovil>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.automovil")]
public partial class automovil : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _codigo;
	
	private string _marca;
	
	private System.Nullable<int> _anio;
	
	private string _modelo;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoChanging(int value);
    partial void OncodigoChanged();
    partial void OnmarcaChanging(string value);
    partial void OnmarcaChanged();
    partial void OnanioChanging(System.Nullable<int> value);
    partial void OnanioChanged();
    partial void OnmodeloChanging(string value);
    partial void OnmodeloChanged();
    #endregion
	
	public automovil()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int codigo
	{
		get
		{
			return this._codigo;
		}
		set
		{
			if ((this._codigo != value))
			{
				this.OncodigoChanging(value);
				this.SendPropertyChanging();
				this._codigo = value;
				this.SendPropertyChanged("codigo");
				this.OncodigoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marca", DbType="VarChar(50)")]
	public string marca
	{
		get
		{
			return this._marca;
		}
		set
		{
			if ((this._marca != value))
			{
				this.OnmarcaChanging(value);
				this.SendPropertyChanging();
				this._marca = value;
				this.SendPropertyChanged("marca");
				this.OnmarcaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anio", DbType="Int")]
	public System.Nullable<int> anio
	{
		get
		{
			return this._anio;
		}
		set
		{
			if ((this._anio != value))
			{
				this.OnanioChanging(value);
				this.SendPropertyChanging();
				this._anio = value;
				this.SendPropertyChanged("anio");
				this.OnanioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modelo", DbType="VarChar(50)")]
	public string modelo
	{
		get
		{
			return this._modelo;
		}
		set
		{
			if ((this._modelo != value))
			{
				this.OnmodeloChanging(value);
				this.SendPropertyChanging();
				this._modelo = value;
				this.SendPropertyChanged("modelo");
				this.OnmodeloChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
